
strategy_name: StateSignal
universe: XLE
tag: rv_regime_15m

assets:
  - XLE

data_path: 'data/gold/model.parquet'

features:
  pipeline: intraday_ohlcv_v1
  return_kind: log
  rv_windows: [5, 20]
  mom_windows: [20, 60]


params:
  state_var: XLE_rvol
  w_low: 0
  w_high: 1.0
