run: 
  strategy_name: StateSignal
  universe: XLE
  tag: rv_regime_5m

  assets:
    - XLE

  data_path: 'data/gold/freq=1D/tag=model_ready/table.parquet'

  params:
    state_var: XLE_rvol
    min_frac: 0.0
    w_low: 0
    w_high: 3.0



live:
  retrain_freq: "1D"
  train_lookback_bars: 504
  min_train_bars: 200