storage:
  config: "steps/storage.yaml"

sources:
  config: "steps/sources.yaml"


ingestion:
  enabled: false
  config: "steps/ingestion.yaml"

silver:
  enabled: false

gold:
  enabled: false
  config: "steps/build_model_table.yaml"

signal:
  enabled: false
  config: "strategies/run_state.yaml"

execution:
  enabled: true
  config: "steps/execution.yaml"
